/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as HiddenFilesRouteImport } from './routes/hidden-files'
import { Route as NewScanRouteImport } from './routes/new-scan'
import { Route as TimestampsRouteImport } from './routes/timestamps'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenFilesRoute = HiddenFilesRouteImport.update({
  id: '/hidden-files',
  path: '/hidden-files',
  getParentRoute: () => rootRouteImport,
} as any)
const NewScanRoute = NewScanRouteImport.update({
  id: '/new-scan',
  path: '/new-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TimestampsRoute = TimestampsRouteImport.update({
  id: '/timestamps',
  path: '/timestamps',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/hidden-files': typeof HiddenFilesRoute
  '/new-scan': typeof NewScanRoute
  '/timestamps': typeof TimestampsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/hidden-files': typeof HiddenFilesRoute
  '/new-scan': typeof NewScanRoute
  '/timestamps': typeof TimestampsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/hidden-files': typeof HiddenFilesRoute
  '/new-scan': typeof NewScanRoute
  '/timestamps': typeof TimestampsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/evidence' | '/hidden-files' | '/new-scan' | '/timestamps'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evidence' | '/hidden-files' | '/new-scan' | '/timestamps'
  id:
    | '__root__'
    | '/'
    | '/evidence'
    | '/hidden-files'
    | '/new-scan'
    | '/timestamps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceRoute: typeof EvidenceRoute
  HiddenFilesRoute: typeof HiddenFilesRoute
  NewScanRoute: typeof NewScanRoute
  TimestampsRoute: typeof TimestampsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-files': {
      id: '/hidden-files'
      path: '/hidden-files'
      fullPath: '/hidden-files'
      preLoaderRoute: typeof HiddenFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-scan': {
      id: '/new-scan'
      path: '/new-scan'
      fullPath: '/new-scan'
      preLoaderRoute: typeof NewScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timestamps': {
      id: '/timestamps'
      path: '/timestamps'
      fullPath: '/timestamps'
      preLoaderRoute: typeof TimestampsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceRoute: EvidenceRoute,
  HiddenFilesRoute: HiddenFilesRoute,
  NewScanRoute: NewScanRoute,
  TimestampsRoute: TimestampsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
